/**
 * đối tượng nhận khi SignIn
 * { globalConfig: { notification: 'NO' },
      speciesProperty: { salesCode: null },
      username: 'lk0618d001',
      webConfigs: [],
      organizationIds: [ '5c34755faf9737c702c16536' ],
      roleIds: [ '5c35dfb6042af62a78880547' ],
      firstName: '',
      lastName: '',
      email: 'lk0618d001@gmail.com',
      support_agent: false,
      plivo_username: '',
      plivo_updated_username: '',
      plivo_status: 0,
      plivo_pwd: '',
      plivo_CallUUID: '',
      plivo_endpoint_id: '',
      plivo_phone_number: '',
      isActive: true,
      description: null,
      isDeleted: false,
      phoneNumber: '0966123454',
      timeFormat: 12,
      startTime: '',
      stopTime: '',
      useType: null,
      freshchatRestoreId: '9a85f708-86da-42a2-a8ec-d8c4836c28f2',
      last_password_change_date: '2020-08-05T03:35:02.459Z',
      last_password_change: null,
      socketIds: [],
      _id: '5c35deaa8cb02c7603b7eebf',
      displayName: 'Nguyễn Hùng Mạnh',
      masterId: '5bff569fa59c5d4b5e9b1629',
      driverInfo: 
       { typeOfVehicle: 'truck',
         driverLicenseNumber: 'LK456',
         deactive: false },
      createdAt: '2019-01-09T11:44:42.821Z',
      __v: 0,
      bqSynced: true,
      lastUpdatedAt: '2020-08-05T03:37:39.921Z',
      pwd_warning: '',
      passwordWarnings: '',
      strongPasswordWarning: null,
      data: 
       { globalConfig: { notification: 'NO' },
         speciesProperty: { salesCode: null },
         username: 'lk0618d001',
         webConfigs: [],
         organizationIds: [ '5c34755faf9737c702c16536' ],
         roleIds: [ '5c35dfb6042af62a78880547' ],
         firstName: '',
         lastName: '',
         email: 'lk0618d001@gmail.com',
         support_agent: false,
         plivo_username: '',
         plivo_updated_username: '',
         plivo_status: 0,
         plivo_pwd: '',
         plivo_CallUUID: '',
         plivo_endpoint_id: '',
         plivo_phone_number: '',
         isActive: true,
         description: null,
         isDeleted: false,
         phoneNumber: '0966123454',
         timeFormat: 12,
         startTime: '',
         stopTime: '',
         useType: null,
         freshchatRestoreId: '9a85f708-86da-42a2-a8ec-d8c4836c28f2',
         last_password_change_date: '2020-08-05T03:35:02.459Z',
         last_password_change: null,
         socketIds: [],
         _id: '5c35deaa8cb02c7603b7eebf',
         displayName: 'Nguyễn Hùng Mạnh',
         masterId: '5bff569fa59c5d4b5e9b1629',
         driverInfo: 
          { typeOfVehicle: 'truck',
            driverLicenseNumber: 'LK456',
            deactive: false },
         createdAt: '2019-01-09T11:44:42.821Z',
         __v: 0,
         bqSynced: true,
         lastUpdatedAt: '2020-08-05T03:37:39.921Z',
         pwd_warning: '',
         passwordWarnings: '',
         strongPasswordWarning: null } }
 */
export interface ISignIn {

    globalConfig: { notification: string },

    speciesProperty: { salesCode: any },

    username: string,
    webConfigs: any[],
    organizationIds: string[],
    roleIds: string[],
    firstName: string,
    lastName: string,
    email: string,
    support_agent: boolean,
    plivo_username: string,
    plivo_updated_username: string,
    plivo_status: number,
    plivo_pwd: string,
    plivo_CallUUID: string,
    plivo_endpoint_id: string,
    plivo_phone_number: string,
    isActive: true,
    description: string,
    isDeleted: boolean,
    phoneNumber: string,
    timeFormat: number,
    startTime: string,
    stopTime: string,
    useType: any,
    freshchatRestoreId: string,
    last_password_change_date: string,
    last_password_change: any,
    socketIds: [],
    _id: string,
    displayName: string,
    masterId: string,
    driverInfo:
    {
        typeOfVehicle: string,
        driverLicenseNumber: string,
        deactive: boolean
    },
    createdAt: string,
    __v: number,
    bqSynced: true,
    lastUpdatedAt: string,
    pwd_warning: string,
    passwordWarnings: string,
    strongPasswordWarning: any,
    data:
    {
        globalConfig: { notification: string },
        speciesProperty: { salesCode: any },
        username: string,
        webConfigs: [],
        organizationIds: string[],
        roleIds: string[],
        firstName: string,
        lastName: string,
        email: string,
        support_agent: boolean,
        plivo_username: string,
        plivo_updated_username: string,
        plivo_status: 0,
        plivo_pwd: string,
        plivo_CallUUID: string,
        plivo_endpoint_id: string,
        plivo_phone_number: string,
        isActive: true,
        description: string,
        isDeleted: boolean,
        phoneNumber: string,
        timeFormat: number,
        startTime: string,
        stopTime: string,
        useType: any,
        freshchatRestoreId: string,
        last_password_change_date: string,
        last_password_change: any,
        socketIds: [],
        _id: string,
        displayName: string,
        masterId: string,
        driverInfo:
        {
            typeOfVehicle: string,
            driverLicenseNumber: string,
            deactive: boolean
        },
        createdAt: string,
        __v: 0,
        bqSynced: boolean,
        lastUpdatedAt: string,
        pwd_warning: string,
        passwordWarnings: string,
        strongPasswordWarning: any
    }
}