
export const SURVEY_ANSWER_TYPE = {
  NUMBER: "NUMBER",
  BOOLEAN: "BOOLEAN",
  SOS: "SOS",
  SOD: "SOD",
  PSKU: "PSKU",
};

export const survey_attributes = {
  703: {
    AttributeCode: 703,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Ariel and Downy detergent are not beside each other",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NG Ariel & NG Downy không nằm cạnh nhau",
  },
  704: {
    AttributeCode: 704,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: ">40% of P&G liquid shelf space on >3kg pack sizes",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: ">40% quầy kệ NG P&G (Ariel & Downy) dành cho chai/túi trên 3kg",
  },
  706: {
    AttributeCode: 706,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Is Liquid scent tester available at eye-level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Mẫu Thử Nước giặt đặt ngang tầm mắt",
  },
  708: {
    AttributeCode: 708,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Liquid shelf at Eye Level for MM/CVS",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Quầy kệ nước giặt nằm ngang tầm mắt cho MM/CVS",
  },
  711: {
    AttributeCode: 711,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Refill 2.3L above >= 50%",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: ">= 50% quầy kệ dành cho Túi từ size 2.3L trở lên",
  },
  712: {
    AttributeCode: 712,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Is Downy scent tester available at eye-level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Mẫu Thử Nước xả vải đặt ngang tầm mắt",
  },
  719: {
    AttributeCode: 719,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have core collection on display: Pantene Hair Fall Control/3MM/Silky Smooth Care, H&S Ultra Men Cool Methol/Cool Methol/Itchy Scapl Care, Rejoice Perfum Smooth/Rich",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có đủ các variant chủ lực không? Pantene Ngăn Rụng/3 Phút Diệu Kỳ/Mượt Mà Óng Ả, H&S Ultra Men Bạc Hà/H&S Bạc Hà/ Da Đầu ngứa/Hương Chanh; Rejoice Hoa Mẫu Đơn/Siêu Mượt.",
  },
  720: {
    AttributeCode: 720,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS ≥ G2X Target",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS >= Chỉ tiêu G2X (25%)",
  },
  721: {
    AttributeCode: 721,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOD ≥ 41%",
    answerType: "SOD",
    AnswerType: "SOD",
    question: "Thị phần trưng bày >= 41%",
  },
  722: {
    AttributeCode: 722,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Golden River Executed from top to bottom shelf. Store >1 bay 1.2m have minim 4 facings",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên quầy kệ có trưng bày Golden River (Dòng Sông Vàng Dầu Xả 3MM?) =>từ 4 mâm trở lên",
  },
  724: {
    AttributeCode: 724,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have horizontal variant shelving from small to big, variant order follow planogram?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Quầy kệ có trưng bày theo hàng ngang: từ size bé đến size lớn & các màu theo planogram của siêu thị.",
  },
  725: {
    AttributeCode: 725,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have horizontal variant shelving from small to big, variant order follow planogram?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Quầy kệ có trưng bày theo hàng ngang: từ size bé đến size lớn & các màu theo planogram của siêu thị.",
  },
  726: {
    AttributeCode: 726,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have horizontal variant shelving from small to big, variant order follow planogram?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Quầy kệ có trưng bày theo hàng ngang: từ size bé đến size lớn & các màu theo planogram của siêu thị.",
  },
  727: {
    AttributeCode: 727,
    Weightage: 20,
    Target: 20,
    PE: "SBD",
    Description: "Do we have horizontal variant shelving from small to big, varian order follow planogram",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Đúng planogram: trưng bày variant theo hàng ngang, từ size nhỏ đến lớn, thứ tự variant theo đúng planogram triển khai",
  },
  728: {
    AttributeCode: 728,
    Weightage: 20,
    Target: 20,
    PE: "SBD",
    Description: "Do we have horizontal variant shelving from small to big, varian order follow planogram",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Đúng planogram: trưng bày variant theo hàng ngang, từ size nhỏ đến lớn, thứ tự variant theo đúng planogram triển khai",
  },
  729: {
    AttributeCode: 729,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Shampoo + Condi display together at strategic location?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Dầu gội & Dầu Xả cùng nhãn hàng nằm cạnh nhau ở vị trí chiến lược (Pantene, Rejoice)",
  },
  730: {
    AttributeCode: 730,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Shampoo + Condi display together at strategic location?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Dầu gội & Dầu Xả cùng nhãn hàng nằm cạnh nhau ở vị trí chiến lược (Pantene, Rejoice)",
  },
  731: {
    AttributeCode: 731,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Shampoo + Condi display together at strategic location?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Dầu gội & Dầu Xả cùng nhãn hàng nằm cạnh nhau ở vị trí chiến lược (Pantene, Rejoice)",
  },
  732: {
    AttributeCode: 732,
    Weightage: 20,
    Target: 20,
    PE: "SBD",
    Description: "Do we have Shampoo + Condi display together at strategic location?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày Gội & Xả của cùng 1 nhãn hiệu ở vị trí chiến lược (áp dụng cho PTN, REJ, HE)",
  },
  733: {
    AttributeCode: 733,
    Weightage: 20,
    Target: 20,
    PE: "SBD",
    Description: "Do we have Shampoo + Condi display together at strategic location?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày Gội & Xả của cùng 1 nhãn hiệu ở vị trí chiến lược (áp dụng cho PTN, REJ, HE)",
  },
  737: {
    AttributeCode: 737,
    Weightage: 60,
    Target: 95,
    PE: "PSKU",
    Description: "P sku distribution >= 95%?",
    answerType: "PSKU",
    AnswerType: "PSKU",
    question: "P sku >= 95%?",
  },
  738: {
    AttributeCode: 738,
    Weightage: 60,
    Target: 95,
    PE: "PSKU",
    Description: "P sku distribution >= 95%?",
    answerType: "PSKU",
    AnswerType: "PSKU",
    question: "P sku >= 95%?",
  },
  742: {
    AttributeCode: 742,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Touch & Feel sample at shelf?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên kệ có mẫu thử để khách hàng sờ thử và cảm nhận không?",
  },
  743: {
    AttributeCode: 743,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have claim on shelf (shelf talker, shelf frame)?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên quầy kệ chính có thông tin nhãn hiệu không? (shelf talker hoặc khung frame)",
  },
  745: {
    AttributeCode: 745,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do Pampers have FSD ?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Tã có đầy đủ các size M - L - XL - XXL?",
  },
  750: {
    AttributeCode: 750,
    Weightage: 40,
    Target: 95,
    PE: "PSKU",
    Description: "P-SKU > 95% ?",
    answerType: "PSKU",
    AnswerType: "PSKU",
    question: "Phân phối sản phẩm chủ lực (P sku) = 95%",
  },
  751: {
    AttributeCode: 751,
    Weightage: 40,
    Target: 95,
    PE: "PSKU",
    Description: "P-SKU > 95% ?",
    answerType: "PSKU",
    AnswerType: "PSKU",
    question: "Phân phối sản phẩm chủ lực (P sku) = 95%",
  },
  756: {
    AttributeCode: 756,
    Weightage: 30,
    Target: 30,
    PE: "SBD",
    Description: "Does GLT open for sales without store assistant",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Gillette có được trưng bày bán mà không đưa vào tủ khóa lại?",
  },
  757: {
    AttributeCode: 757,
    Weightage: 30,
    Target: 30,
    PE: "SBD",
    Description: "Does GLT open for sales without store assistant",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Gillette có được trưng bày bán mà không đưa vào tủ khóa lại?",
  },
  758: {
    AttributeCode: 758,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "Thị phần quầy kệ >= 60%",
  },
  762: {
    AttributeCode: 762,
    Weightage: 30,
    Target: 30,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "Thị phần quầy kệ >= 60%",
  },
  763: {
    AttributeCode: 763,
    Weightage: 30,
    Target: 30,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "Thị phần quầy kệ >= 60%",
  },
  764: {
    AttributeCode: 764,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Best – Better – Good execution on shelf",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có trưng bày ngoài quầy kệ theo planogram Tốt - Tốt Hơn - Tốt Nhất?",
  },
  768: {
    AttributeCode: 768,
    Weightage: 0,
    Target: 0,
    PE: "SBD",
    Description: "Best – Better – Good execution on shelf",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có trưng bày ngoài quầy kệ theo planogram Tốt - Tốt Hơn - Tốt Nhất?",
  },
  769: {
    AttributeCode: 769,
    Weightage: 0,
    Target: 0,
    PE: "SBD",
    Description: "Best – Better – Good execution on shelf",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có trưng bày ngoài quầy kệ theo planogram Tốt - Tốt Hơn - Tốt Nhất?",
  },
  771: {
    AttributeCode: 771,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does Gillette have at least 1 display at the check-count counter?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có ít nhất 1 trưng bày tại khu vực quầy tính tiền.",
  },
  772: {
    AttributeCode: 772,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does Gillette have at least 1 display at the check-count counter?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có ít nhất 1 trưng bày tại khu vực quầy tính tiền.",
  },
  773: {
    AttributeCode: 773,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does Gillette have at least 1 display at the check-count counter?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có ít nhất 1 trưng bày tại khu vực quầy tính tiền.",
  },
  774: {
    AttributeCode: 774,
    Weightage: 0,
    Target: 0,
    PE: "SBD",
    Description: "Does Gillette have at least 1 display at the check-count counter",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có trưng bày ngoài quầy kệ tại Cashier?",
  },
  775: {
    AttributeCode: 775,
    Weightage: 0,
    Target: 0,
    PE: "SBD",
    Description: "Does Gillette have at least 1 display at the check-count counter",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có trưng bày ngoài quầy kệ tại Cashier?",
  },
  903: {
    AttributeCode: 903,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Ariel and Downy detergent are not beside each other",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NG Ariel & NG Downy không nằm cạnh nhau",
  },
  904: {
    AttributeCode: 904,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Ariel and Downy detergent are not beside each other",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NG Ariel & NG Downy không nằm cạnh nhau",
  },
  905: {
    AttributeCode: 905,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Ariel and Downy detergent are not beside each other",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NG Ariel & NG Downy không nằm cạnh nhau",
  },
  906: {
    AttributeCode: 906,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: ">40% of P&G liquid shelf space on >3kg pack sizes",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: ">40% quầy kệ NG P&G (Ariel & Downy) dành cho chai/túi trên 3kg",
  },
  907: {
    AttributeCode: 907,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: ">40% of P&G liquid shelf space on >3kg pack sizes",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: ">40% quầy kệ NG P&G (Ariel & Downy) dành cho chai/túi trên 3kg",
  },
  908: {
    AttributeCode: 908,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: ">40% of P&G liquid shelf space on >3kg pack sizes",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: ">40% quầy kệ NG P&G (Ariel & Downy) dành cho chai/túi trên 3kg",
  },
  909: {
    AttributeCode: 909,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Is Liquid scent tester available at eye-level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Mẫu Thử Nước giặt đặt ngang tầm mắt",
  },
  910: {
    AttributeCode: 910,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Is Liquid scent tester available at eye-level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Mẫu Thử Nước giặt đặt ngang tầm mắt",
  },
  911: {
    AttributeCode: 911,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Is Liquid scent tester available at eye-level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Mẫu Thử Nước giặt đặt ngang tầm mắt",
  },
  921: {
    AttributeCode: 921,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Refill 2.3L above >= 50%",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: ">= 50% quầy kệ dành cho Túi từ size 2.3L trở lên",
  },
  922: {
    AttributeCode: 922,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Refill 2.3L above >= 50%",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: ">= 50% quầy kệ dành cho Túi từ size 2.3L trở lên",
  },
  923: {
    AttributeCode: 923,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Refill 2.3L above >= 50%",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: ">= 50% quầy kệ dành cho Túi từ size 2.3L trở lên",
  },
  924: {
    AttributeCode: 924,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Is Downy scent tester available at eye-level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Mẫu Thử Nước xả vải đặt ngang tầm mắt",
  },
  925: {
    AttributeCode: 925,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Is Downy scent tester available at eye-level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Mẫu Thử Nước xả vải đặt ngang tầm mắt",
  },
  926: {
    AttributeCode: 926,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Is Downy scent tester available at eye-level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Mẫu Thử Nước xả vải đặt ngang tầm mắt",
  },
  933: {
    AttributeCode: 933,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have core collection on display: Pantene Hair Fall Control/3MM/Silky Smooth Care, H&S Ultra Men Cool Methol/Cool Methol/Itchy Scapl Care, Rejoice Perfum Smooth/Rich",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có đủ các variant chủ lực không? Pantene Ngăn Rụng/3 Phút Diệu Kỳ/Mượt Mà Óng Ả, H&S Ultra Men Bạc Hà/H&S Bạc Hà/ Da Đầu ngứa/Hương Chanh; Rejoice Hoa Mẫu Đơn/Siêu Mượt.",
  },
  934: {
    AttributeCode: 934,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have core collection on display: Pantene Hair Fall Control/3MM/Silky Smooth Care, H&S Ultra Men Cool Methol/Cool Methol/Itchy Scapl Care, Rejoice Perfum Smooth/Rich",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có đủ các variant chủ lực không? Pantene Ngăn Rụng/3 Phút Diệu Kỳ/Mượt Mà Óng Ả, H&S Ultra Men Bạc Hà/H&S Bạc Hà/ Da Đầu ngứa/Hương Chanh; Rejoice Hoa Mẫu Đơn/Siêu Mượt.",
  },
  935: {
    AttributeCode: 935,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have core collection on display: Pantene Hair Fall Control/3MM/Silky Smooth Care, H&S Ultra Men Cool Methol/Cool Methol/Itchy Scapl Care, Rejoice Perfum Smooth/Rich",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có đủ các variant chủ lực không? Pantene Ngăn Rụng/3 Phút Diệu Kỳ/Mượt Mà Óng Ả, H&S Ultra Men Bạc Hà/H&S Bạc Hà/ Da Đầu ngứa/Hương Chanh; Rejoice Hoa Mẫu Đơn/Siêu Mượt.",
  },
  939: {
    AttributeCode: 939,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOD ≥ 41%",
    answerType: "SOD",
    AnswerType: "SOD",
    question: "Thị phần trưng bày >= 41%",
  },
  940: {
    AttributeCode: 940,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOD ≥ 41%",
    answerType: "SOD",
    AnswerType: "SOD",
    question: "Thị phần trưng bày >= 41%",
  },
  941: {
    AttributeCode: 941,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOD ≥ 41%",
    answerType: "SOD",
    AnswerType: "SOD",
    question: "Thị phần trưng bày >= 41%",
  },
  942: {
    AttributeCode: 942,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Golden River Executed from top to bottom shelf. Store >1 bay 1.2m have minim 4 facings",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên quầy kệ có trưng bày Golden River (Dòng Sông Vàng Dầu Xả 3MM?) =>từ 4 mâm trở lên",
  },
  943: {
    AttributeCode: 943,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Golden River Executed from top to bottom shelf. Store >1 bay 1.2m have minim 4 facings",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên quầy kệ có trưng bày Golden River (Dòng Sông Vàng Dầu Xả 3MM?) =>từ 4 mâm trở lên",
  },
  944: {
    AttributeCode: 944,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Golden River Executed from top to bottom shelf. Store >1 bay 1.2m have minim 4 facings",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên quầy kệ có trưng bày Golden River (Dòng Sông Vàng Dầu Xả 3MM?) =>từ 4 mâm trở lên",
  },
  954: {
    AttributeCode: 954,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does Pampers M shelf at eye level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Tả quần Pampers size M có được trưng bày trên kệ ngang tầm mắt của khách hàng không?",
  },
  955: {
    AttributeCode: 955,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does Pampers M shelf at eye level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Tả quần Pampers size M có được trưng bày trên kệ ngang tầm mắt của khách hàng không?",
  },
  956: {
    AttributeCode: 956,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does Pampers M shelf at eye level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Tả quần Pampers size M có được trưng bày trên kệ ngang tầm mắt của khách hàng không?",
  },
  957: {
    AttributeCode: 957,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Touch & Feel sample at shelf?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên kệ có mẫu thử để khách hàng sờ thử và cảm nhận không?",
  },
  958: {
    AttributeCode: 958,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Touch & Feel sample at shelf?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên kệ có mẫu thử để khách hàng sờ thử và cảm nhận không?",
  },
  959: {
    AttributeCode: 959,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have Touch & Feel sample at shelf?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên kệ có mẫu thử để khách hàng sờ thử và cảm nhận không?",
  },
  960: {
    AttributeCode: 960,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have claim on shelf (shelf talker, shelf frame)?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên quầy kệ chính có thông tin nhãn hiệu không? (shelf talker hoặc khung frame)",
  },
  961: {
    AttributeCode: 961,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have claim on shelf (shelf talker, shelf frame)?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên quầy kệ chính có thông tin nhãn hiệu không? (shelf talker hoặc khung frame)",
  },
  962: {
    AttributeCode: 962,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have claim on shelf (shelf talker, shelf frame)?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trên quầy kệ chính có thông tin nhãn hiệu không? (shelf talker hoặc khung frame)",
  },
  966: {
    AttributeCode: 966,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do Pampers have FSD ?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Tã có đầy đủ các size M - L - XL - XXL?",
  },
  967: {
    AttributeCode: 967,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do Pampers have FSD ?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Tã có đầy đủ các size M - L - XL - XXL?",
  },
  968: {
    AttributeCode: 968,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do Pampers have FSD ?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Tã có đầy đủ các size M - L - XL - XXL?",
  },
  975: {
    AttributeCode: 975,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "Thị phần quầy kệ >= 60%",
  },
  976: {
    AttributeCode: 976,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "Thị phần quầy kệ >= 60%",
  },
  977: {
    AttributeCode: 977,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "Thị phần quầy kệ >= 60%",
  },
  978: {
    AttributeCode: 978,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Best – Better – Good execution on shelf",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có trưng bày ngoài quầy kệ theo planogram Tốt - Tốt Hơn - Tốt Nhất?",
  },
  979: {
    AttributeCode: 979,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Best – Better – Good execution on shelf",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có trưng bày ngoài quầy kệ theo planogram Tốt - Tốt Hơn - Tốt Nhất?",
  },
  980: {
    AttributeCode: 980,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Best – Better – Good execution on shelf",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có trưng bày ngoài quầy kệ theo planogram Tốt - Tốt Hơn - Tốt Nhất?",
  },
  990: {
    AttributeCode: 990,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have right assortment in COC ? (only carry following SKUs: M3 cart 4S, Vector card 4S, Preps)",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có theo đúng chuẩn được triền khai? (bao gồm Lưỡi Gillette Mach3 4s, Lưỡi Vector 4s, Bọt cạo râu – Lưỡi 4s cho Hyper/Super, Lưỡi 2s cho các phân mảng còn lại)",
  },
  991: {
    AttributeCode: 991,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have right assortment in COC ? (only carry following SKUs: M3 cart 4S, Vector card 4S, Preps)",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có theo đúng chuẩn được triền khai? (bao gồm Lưỡi Gillette Mach3 4s, Lưỡi Vector 4s, Bọt cạo râu – Lưỡi 4s cho Hyper/Super, Lưỡi 2s cho các phân mảng còn lại)",
  },
  992: {
    AttributeCode: 992,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have right assortment in COC ? (only carry following SKUs: M3 cart 4S, Vector card 4S, Preps)",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có theo đúng chuẩn được triền khai? (bao gồm Lưỡi Gillette Mach3 4s, Lưỡi Vector 4s, Bọt cạo râu – Lưỡi 4s cho Hyper/Super, Lưỡi 2s cho các phân mảng còn lại)",
  },
  994: {
    AttributeCode: 994,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Maintain # of stores having sensitive blocks vs 2H 1920",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NXV Downy Dịu Nhẹ Tinh Khiết nằm cạnh NXV Comfort Dịu Nhẹ (chỉ áp dụng cho các store đã có Phân khúc Dịu Nhẹ vào cuối tháng 6/2020)",
  },
  995: {
    AttributeCode: 995,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Gondola End or Pallet display at either Fabric care Category Aisle or check out",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Vị trí Trưng bày của Nước xả vải nằm gần khu vực Quầy kệ chính Hoặc khu vực tính tiền",
  },
  996: {
    AttributeCode: 996,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Share of Shelf for Big Bottle > value share for Big Bottle",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Thị phần quầy kệ size lớn (từ 800ml trở lên) lớn hơn thị phần doanh số của size này cho các nhãn hàng Pantene/Rejoice/H&S",
  },
  997: {
    AttributeCode: 997,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does gillette have 50% Check out penetration?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "50% Số lượng quầy tính tiền trong siêu thị có trưng bày Gillette?",
  },
  998: {
    AttributeCode: 998,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does Gillette have at least 1 display in-store (excl check out display & mainshelf)?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có ít nhất 1 trưng bày ngoài quầy kệ chính & khu vực Cashier.",
  },
  999: {
    AttributeCode: 999,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "Thị phần quầy kệ lớn hơn năm trước (tính kết quả tháng 6/2020)",
  },
  1000: {
    AttributeCode: 1000,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Liquid shelf at Eye Level for MM/CVS",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Quầy kệ nước giặt nằm ngang tầm mắt cho MM/CVS",
  },
  1001: {
    AttributeCode: 1001,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Liquid shelf at Eye Level for MM/CVS",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Quầy kệ nước giặt nằm ngang tầm mắt cho MM/CVS",
  },
  1002: {
    AttributeCode: 1002,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "Thị phần quầy kệ lớn hơn năm trước (tính kết quả tháng 6/2020)",
  },
  1003: {
    AttributeCode: 1003,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Gondola End or Pallet display at either Fabric care Category Aisle or check out",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Vị trí Trưng bày của Bột Giặt & Nước Giặt nằm gần khu vực Quầy kệ chính Hoặc khu vực tính tiền",
  },
  1004: {
    AttributeCode: 1004,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Gondola End or Pallet display at either Fabric care Category Aisle or check out",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Vị trí Trưng bày của Bột Giặt & Nước Giặt nằm gần khu vực Quầy kệ chính Hoặc khu vực tính tiền",
  },
  1005: {
    AttributeCode: 1005,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Gondola End or Pallet display at either Fabric care Category Aisle or check out",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Vị trí Trưng bày của Bột Giặt & Nước Giặt nằm gần khu vực Quầy kệ chính Hoặc khu vực tính tiền",
  },
  1006: {
    AttributeCode: 1006,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Gondola End or Pallet display at either Fabric care Category Aisle or check out",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Vị trí Trưng bày của Bột Giặt & Nước Giặt nằm gần khu vực Quầy kệ chính Hoặc khu vực tính tiền",
  },
  1007: {
    AttributeCode: 1007,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Ariel/Tide/Downy Laundry in clear brand blocks",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NG Ariel, BG Tide & NG Downy được block theo từng nhãn",
  },
  1008: {
    AttributeCode: 1008,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Ariel/Tide/Downy Laundry in clear brand blocks",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NG Ariel, BG Tide & NG Downy được block theo từng nhãn",
  },
  1009: {
    AttributeCode: 1009,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Ariel/Tide/Downy Laundry in clear brand blocks",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NG Ariel, BG Tide & NG Downy được block theo từng nhãn",
  },
  1010: {
    AttributeCode: 1010,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1011: {
    AttributeCode: 1011,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1012: {
    AttributeCode: 1012,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1013: {
    AttributeCode: 1013,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1014: {
    AttributeCode: 1014,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Gondola End or Pallet display at either Fabric care Category Aisle or check out",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Vị trí Trưng bày của Nước xả vải nằm gần khu vực Quầy kệ chính Hoặc khu vực tính tiền",
  },
  1015: {
    AttributeCode: 1015,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Downy FE at eye-level",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Nước xả vải Downy nằm ngang tầm mắt cho MM/CVS",
  },
  1016: {
    AttributeCode: 1016,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Downy FE at eye-level",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Nước xả vải Downy nằm ngang tầm mắt cho MM/CVS",
  },
  1017: {
    AttributeCode: 1017,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Downy FE at eye-level",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Nước xả vải Downy nằm ngang tầm mắt cho MM/CVS",
  },
  1018: {
    AttributeCode: 1018,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1019: {
    AttributeCode: 1019,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1020: {
    AttributeCode: 1020,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1021: {
    AttributeCode: 1021,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1022: {
    AttributeCode: 1022,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1023: {
    AttributeCode: 1023,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1024: {
    AttributeCode: 1024,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Maintain # of stores having sensitive blocks vs 2H 1920",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NXV Downy Dịu Nhẹ Tinh Khiết nằm cạnh NXV Comfort Dịu Nhẹ (chỉ áp dụng cho các store đã có Phân khúc Dịu Nhẹ vào cuối tháng 6/2020)",
  },
  1025: {
    AttributeCode: 1025,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Brand Block for Downy",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NXV Downy được block theo nhãn trên kệ chính",
  },
  1026: {
    AttributeCode: 1026,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Brand Block for Downy",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NXV Downy được block theo nhãn trên kệ chính",
  },
  1027: {
    AttributeCode: 1027,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Brand Block for Downy",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "NXV Downy được block theo nhãn trên kệ chính",
  },
  1028: {
    AttributeCode: 1028,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1029: {
    AttributeCode: 1029,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Share of Shelf for Big Bottle > value share for Big Bottle",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Thị phần quầy kệ size lớn (từ 800ml trở lên) lớn hơn thị phần doanh số của size này cho các nhãn hàng Pantene/Rejoice/H&S",
  },
  1030: {
    AttributeCode: 1030,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1031: {
    AttributeCode: 1031,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1032: {
    AttributeCode: 1032,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1034: {
    AttributeCode: 1034,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does Pampers M shelf at eye level?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Tả quần Pampers size M có được trưng bày trên kệ ngang tầm mắt của khách hàng không?",
  },
  1035: {
    AttributeCode: 1035,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "SOS > 60%",
  },
  1036: {
    AttributeCode: 1036,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "SOS > 60%",
    answerType: "SOS",
    AnswerType: "SOS",
    question: "Thị phần quầy kệ lớn hơn năm trước (tính kết quả tháng 6/2020)",
  },
  1037: {
    AttributeCode: 1037,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does gillette have 50% Check out penetration?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "50% Số lượng quầy tính tiền trong siêu thị có trưng bày Gillette?",
  },
  1038: {
    AttributeCode: 1038,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have right assortment in COC ? (only carry following SKUs: M3 cart 4S, Vector card 4S, Preps)",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có theo đúng chuẩn được triền khai? (bao gồm Lưỡi Gillette Mach3 4s, Lưỡi Vector 4s, Bọt cạo râu – Lưỡi 4s cho Hyper/Super, Lưỡi 2s cho các phân mảng còn lại)",
  },
  1039: {
    AttributeCode: 1039,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have right assortment in COC ? (only carry following SKUs: M3 cart 4S, Vector card 4S, Preps)",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có theo đúng chuẩn được triền khai? (bao gồm Lưỡi Gillette Mach3 4s, Lưỡi Vector 4s, Bọt cạo râu – Lưỡi 4s cho Hyper/Super, Lưỡi 2s cho các phân mảng còn lại)",
  },
  1040: {
    AttributeCode: 1040,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have right assortment in COC ? (only carry following SKUs: M3 cart 4S, Vector card 4S, Preps)",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có theo đúng chuẩn được triền khai? (bao gồm Lưỡi Gillette Mach3 4s, Lưỡi Vector 4s, Bọt cạo râu – Lưỡi 4s cho Hyper/Super, Lưỡi 2s cho các phân mảng còn lại)",
  },
  1041: {
    AttributeCode: 1041,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Do we have right assortment in COC ? (only carry following SKUs: M3 cart 4S, Vector card 4S, Preps)",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Trưng bày ngoài quầy kệ có theo đúng chuẩn được triền khai? (bao gồm Lưỡi Gillette Mach3 4s, Lưỡi Vector 4s, Bọt cạo râu – Lưỡi 4s cho Hyper/Super, Lưỡi 2s cho các phân mảng còn lại)",
  },
  1042: {
    AttributeCode: 1042,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Does Gillette have at least 1 display in-store (excl check out display & mainshelf)?",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có ít nhất 1 trưng bày ngoài quầy kệ chính & khu vực Cashier.",
  },
  1043: {
    AttributeCode: 1043,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Mainshelf existence in store",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có khu vực quầy kệ chính (nằm ngoài khu vực Quầy tính tiền)?",
  },
  1044: {
    AttributeCode: 1044,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Mainshelf existence in store",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có khu vực quầy kệ chính (nằm ngoài khu vực Quầy tính tiền)?",
  },
  1045: {
    AttributeCode: 1045,
    Weightage: 1,
    Target: 1,
    PE: "SBD",
    Description: "Mainshelf existence in store",
    answerType: "BOOLEAN",
    AnswerType: "BOOLEAN",
    question: "Cửa hàng có khu vực quầy kệ chính (nằm ngoài khu vực Quầy tính tiền)?",
  },
};
