export const components = [
  {
    isNew: false,
    properties: {
      '': '',
    },
    conditional: {
      eq: '',
      when: null,
      show: '',
    },
    tags: [],
    type: 'select',
    validate: {
      required: false,
    },
    clearOnHide: true,
    hidden: false,
    persistent: true,
    unique: false,
    protected: false,
    multiple: false,
    template: '<span>{{ item.label }}</span>',
    authenticate: false,
    filter: '',
    refreshOn: '',
    defaultValue: '',
    valueProperty: '',
    dataSrc: 'values',
    data: {
      custom: '',
      resource: '',
      url: '',
      json: '',
      values: [
        {
          label: 'ChuongTrinh1',
          value: 'chuongTrinh1',
        },
        {
          label: 'ChuongTrinh2',
          value: 'chuongTrinh2',
        },
      ],
    },
    placeholder: '',
    key: 'undefinedChuongtrinh',
    label: 'Chuong trinh',
    tableView: true,
    input: true,
  },
  {
    properties: {
      '': '',
    },
    conditional: {
      eq: '',
      when: null,
      show: '',
    },
    tags: [],
    breadcrumb: 'default',
    type: 'panel',
    components: [
      {
        properties: {
          '': '',
        },
        conditional: {
          eq: '',
          when: null,
          show: '',
        },
        tags: [],
        type: 'datetime',
        validate: {
          custom: '',
          required: false,
        },
        clearOnHide: true,
        hidden: false,
        persistent: true,
        protected: false,
        timePicker: {
          arrowkeys: true,
          mousewheel: true,
          readonlyInput: false,
          showMeridian: true,
          minuteStep: 1,
          hourStep: 1,
        },
        datePicker: {
          datepickerMode: 'day',
          yearColumns: 5,
          yearRows: 4,
          maxMode: 'year',
          minMode: 'day',
          initDate: '',
          startingDay: 0,
          showWeeks: true,
        },
        datepickerMode: 'day',
        defaultDate: '',
        enableTime: true,
        enableDate: true,
        format: 'yyyy-MM-dd hh:mm a',
        placeholder: '',
        key: 'undefinedPanelDatetimeField',
        label: 'Từ ngày',
        tableView: true,
        input: true,
      },
      {
        properties: {
          '': '',
        },
        conditional: {
          eq: '',
          when: null,
          show: '',
        },
        tags: [],
        type: 'datetime',
        validate: {
          custom: '',
          required: false,
        },
        clearOnHide: true,
        hidden: false,
        persistent: true,
        protected: false,
        timePicker: {
          arrowkeys: true,
          mousewheel: true,
          readonlyInput: false,
          showMeridian: true,
          minuteStep: 1,
          hourStep: 1,
        },
        datePicker: {
          datepickerMode: 'day',
          yearColumns: 5,
          yearRows: 4,
          maxMode: 'year',
          minMode: 'day',
          initDate: '',
          startingDay: 0,
          showWeeks: true,
        },
        datepickerMode: 'day',
        defaultDate: '',
        enableTime: true,
        enableDate: true,
        format: 'yyyy-MM-dd hh:mm a',
        placeholder: '',
        key: 'undefinedPanelTingy',
        label: 'Tới ngày',
        tableView: true,
        input: true,
      },
    ],
    tableView: false,
    theme: 'default',
    title: 'Postmail',
    input: false,
    key: 'undefinedPanel',
  },
  {
    isNew: true,
    type: 'form',
    persistent: true,
    unique: false,
    protected: false,
    label: '',
    path: '',
    form: '',
    reference: true,
    src: '',
    key: 'undefinedFormField',
    tableView: true,
    input: true,
  },
  {
    isNew: true,
    type: 'form',
    persistent: true,
    unique: false,
    protected: false,
    label: '',
    path: '',
    form: '',
    reference: true,
    src: '',
    key: 'undefinedFormField',
    tableView: true,
    input: true,
  },
  {
    properties: {
      '': '',
    },
    conditional: {
      eq: '',
      when: null,
      show: '',
    },
    tags: [],
    breadcrumb: 'default',
    type: 'panel',
    components: [
      {
        properties: {
          '': '',
        },
        conditional: {
          eq: '',
          when: null,
          show: '',
        },
        tags: [],
        type: 'datetime',
        validate: {
          custom: '',
          required: false,
        },
        clearOnHide: true,
        hidden: false,
        persistent: true,
        protected: false,
        timePicker: {
          arrowkeys: true,
          mousewheel: true,
          readonlyInput: false,
          showMeridian: true,
          minuteStep: 1,
          hourStep: 1,
        },
        datePicker: {
          datepickerMode: 'day',
          yearColumns: 5,
          yearRows: 4,
          maxMode: 'year',
          minMode: 'day',
          initDate: '',
          startingDay: 0,
          showWeeks: true,
        },
        datepickerMode: 'day',
        defaultDate: '',
        enableTime: true,
        enableDate: true,
        format: 'yyyy-MM-dd hh:mm a',
        placeholder: '',
        key: 'undefinedPanel2Thct',
        label: 'Thực tế',
        tableView: true,
        input: true,
      },
      {
        properties: {
          '': '',
        },
        conditional: {
          eq: '',
          when: null,
          show: '',
        },
        tags: [],
        type: 'file',
        clearOnHide: true,
        hidden: false,
        persistent: true,
        protected: false,
        defaultValue: '',
        multiple: false,
        placeholder: '',
        imageSize: '200',
        image: false,
        key: 'undefinedPanel2Thmhnhnh',
        label: 'Thêm hình ảnh',
        tableView: true,
        input: true,
      },
    ],
    tableView: false,
    theme: 'default',
    title: 'Tốc độ lên hàng - Speed on Shelf',
    input: false,
    key: 'undefinedPanel2',
  },
  {
    properties: {
      '': '',
    },
    conditional: {
      eq: '',
      when: null,
      show: '',
    },
    tags: [],
    breadcrumb: 'default',
    type: 'panel',
    components: [
      {
        properties: {
          '': '',
        },
        tags: [],
        type: 'textfield',
        conditional: {
          eq: '',
          when: null,
          show: '',
        },
        validate: {
          customPrivate: false,
          custom: '',
          pattern: '',
          maxLength: '',
          minLength: '',
          required: false,
        },
        clearOnHide: true,
        hidden: false,
        persistent: true,
        unique: false,
        protected: false,
        defaultValue: '',
        multiple: false,
        suffix: '',
        prefix: '',
        placeholder: '',
        key: 'undefinedPanel3Chtiu',
        label: 'Chỉ tiêu',
        inputMask: '',
        inputType: 'text',
        tableView: true,
        input: true,
      },
      {
        properties: {
          '': '',
        },
        tags: [],
        type: 'textfield',
        conditional: {
          eq: '',
          when: null,
          show: '',
        },
        validate: {
          customPrivate: false,
          custom: '',
          pattern: '',
          maxLength: '',
          minLength: '',
          required: false,
        },
        clearOnHide: true,
        hidden: false,
        persistent: true,
        unique: false,
        protected: false,
        defaultValue: '',
        multiple: false,
        suffix: '',
        prefix: '',
        placeholder: '',
        key: 'undefinedPanel3Thct',
        label: 'Thực tế',
        inputMask: '',
        inputType: 'text',
        tableView: true,
        input: true,
      },
    ],
    tableView: false,
    theme: 'default',
    title: 'Phân phối - Distribution List in',
    input: false,
    key: 'undefinedPanel3',
  },
  {
    properties: {
      '': '',
    },
    conditional: {
      eq: '',
      when: null,
      show: '',
    },
    tags: [],
    breadcrumb: 'default',
    type: 'panel',
    components: [
      {
        properties: {
          '': '',
        },
        conditional: {
          eq: '',
          when: null,
          show: '',
        },
        tags: [],
        type: 'file',
        clearOnHide: true,
        hidden: false,
        persistent: true,
        protected: false,
        defaultValue: '',
        multiple: false,
        placeholder: '',
        imageSize: '200',
        image: false,
        key: 'undefinedPanel4Thmhnhnh',
        label: 'Quầy kệ chính',
        tableView: true,
        input: true,
      },
      {
        properties: {
          '': '',
        },
        conditional: {
          eq: '',
          when: null,
          show: '',
        },
        tags: [],
        type: 'file',
        clearOnHide: true,
        hidden: false,
        persistent: true,
        protected: false,
        defaultValue: '',
        multiple: false,
        placeholder: '',
        imageSize: '200',
        image: false,
        key: 'undefinedPanel4Thmhnhnh2',
        label: 'Trưng bày',
        tableView: true,
        input: true,
      },
    ],
    tableView: false,
    theme: 'default',
    title: 'Hỉnh ảnh',
    input: false,
    key: 'undefinedPanel4',
  },
];
