export const CHANGE_FINGER_PRINT_SETTING = "CHANGE_FINGER_PRINT_SETTING"
export const ADD_USER_FINGER_PRINT_DATA = "ADD_USER_FINGER_PRINT_DATA"
export const FORCE_FINGER_PRINT = "FORCE_FINGER_PRINT"
export const ADD_REMEMBER_LOGIN_DATA = "ADD_REMEMBER_LOGIN_DATA"