export default {
    REFRESH_TASK_LIST: 'REFRESH_TASK_LIST',
    REFRESH_ORDER_LIST: 'REFRESH_ORDER_LIST',
    REFRESH_PRODUCT_LIST: 'REFRESH_PRODUCT_LIST',
    REFRESH_INVENTORY_LIST: 'REFRESH_INVENTORY_LIST',

    REFRESH_CUSTOMER_LIST: 'REFRESH_CUSTOMER_LIST',
    REFRESH_COMPANY_LIST: 'REFRESH_COMPANY_LIST',


    REFRESH_SHIPMENT_LIST: 'REFRESH_SHIPMENT_LIST',
    REFRESH_CONTAINER_LIST: 'REFRESH_CONTAINER_LIST',

}

