/**
 * Thông tin xe
 * associates: [],
      MDP: 
       [ 'LK0618S001',
         'LK0618S002',
         'LK0618S003',
         'LK0618S004',
         'LK0618S005' ],
      attachedContainerIds: [],
      vehicleCode: 'LKXETAI3',
      vehicleName: null,
      organizationId: '5c34755faf9737c702c16536',
      typeOfVehicle: 'truck',
      capacityWeight: 3000,
      capacityVolume: 7,
      maxDistance: 400,
      licensePlate: 'LK345',
      tempZone: 1,
      isDeleted: false,
      tareWeight: 0,
      realWeight: 0,
      maxGross: 0,
      weightLevel: 0,
      vehicleIdentificationNumber: null,
      vehicleInternalCode: null,
      vehicleEngineNumber: null,
      vehicleDescription: null,
      attachedTrailerId: null,
      vehicleStatus: 'LOCKED',
      planningStatus: 'LOCKED',
      _id: '5c35e4e9ddb3c46ad367999f',
      defaultDriverName: 'Nguyễn Hùng Mạnh',
      fixedCost: 2000000,
      rentCost: 0,
      costPerKm: 2080,
      lunchStopTime: '13:00',
      lunchStartTime: '12:00',
      overtimeHour: '20:00',
      grossVehicleWeight: 3000,
      overtimeRate: '1.3',
      stopTime: '22:00',
      startTime: '4:00',
      speed: 45,
      temperature: 'A',
      defaultDriver: 'lk0618d001',
      deactive: false,
      reserved_to: null,
      reserved_from: null,
      reserved: false,
      sub_con_name: null,
      sub_contractor: false,
      capacityPallete: 1,
      locationId: null,
      cargoLength: null,
      cargoWidth: null,
      cargoHeight: null,
      sub_con_code: ''
 */
export interface IVehicle {
    associates: any[],
    MDP:string[],
    attachedContainerIds: any[],
    vehicleCode: string,
    vehicleName: any,
    organizationId: string,
    typeOfVehicle: string,
    capacityWeight: number,
    capacityVolume: number,
    maxDistance: number,
    licensePlate: string,
    tempZone: number,
    isDeleted: boolean,
    tareWeight: number,
    realWeight: number,
    maxGross: number,
    weightLevel: number,
    vehicleIdentificationNumber: any,
    vehicleInternalCode: any,
    vehicleEngineNumber: any,
    vehicleDescription: any,
    attachedTrailerId: any,
    vehicleStatus: string,
    planningStatus: string,
    _id: string,
    defaultDriverName: string,
    fixedCost: number,
    rentCost: number,
    costPerKm: number,
    lunchStopTime: string,
    lunchStartTime: string,
    overtimeHour: string,
    grossVehicleWeight: number,
    overtimeRate: string,
    stopTime: string,
    startTime: string,
    speed: number,
    temperature: string,
    defaultDriver: string,
    deactive: boolean,
    reserved_to: any,
    reserved_from: any,
    reserved: boolean,
    sub_con_name: any,
    sub_contractor: boolean,
    capacityPallete: 1,
    locationId: any,
    cargoLength: any,
    cargoWidth: any,
    cargoHeight: any,
    sub_con_code: string
}