import AppColors from '../theme/AppColors';

enum TaskCode {
    //Geometry
    SOD = 'SOD',
    INITIATIVE = 'INITIATIVE',
    INITIATIVE_MR = 'INITIATIVE-MR',
    INITIATIVE_IS = 'INITIATIVE-IS',
    INITIATIVE_MM = 'INITIATIVE-MM',
    INITIATIVE_CVS = 'INITIATIVE-CVS',

    INITIATIVE_MMTIER1 = 'INITIATIVE-MM-TIER_1',
    INITIATIVE_MMTIER2 = 'INITIATIVE-MM-TIER_2',
    INITIATIVE_HB = 'INITIATIVE-H&B',
    INITIATIVE_DP = 'INITIATIVE-D&P',

    INITIATIVE_CCC = 'INITIATIVE-CCC',
    INITIATIVE_HM = 'INITIATIVE-HM',
    INITIATIVE_SM = 'INITIATIVE-SM',

    PHOTO_APP = 'PHOTO-APP',

    SOOS = 'SOOS',

    SOS = 'SOS',
    VFAST = 'V-FAST',
    SURVEYHSM = 'SURVEYHSM',
    SURVEYCCC = 'SURVEYCCC',
    SURVEYIS = 'SURVEYIS',
    SURVEYCVS = 'SURVEYCVS',
    SURVEYMM = 'SURVEYMM',
    SURVEYHM = 'SURVEYHM',
    SURVEYSM = 'SURVEYSM',

    SURVEYMM_TIER_1 = 'SURVEYMM-TIER_1',
    SURVEYMM_TIER_2 = 'SURVEYMM-TIER_2',
    SURVEYHB = 'SURVEYH&B',
    SURVEYDP = 'SURVEYD&P',

    CHECK_IN = 'CheckIn',
    CHECK_OUT = 'CheckOut',


    //TMS
    HET_NGAY = 'HET_NGAY',
    GIAO_HANG = 'GIAO_HANG',
    SOAN_HANG = 'SOAN_HANG',
    VE_KHO = 'VE_KHO',
    LOADING_AT_STORE = 'LOADING_AT_STORE',
    TRANSIT = 'TRANSIT',
    EXTRA_TASK = 'EXTRA_TASK',
    //AoSmith
    LAP_DAT = 'LM',
    THAY_THE_LINH_KIEN = 'TT',
    CAP_NHAT_PHAN_MEM = 'CNPM',
    BAO_DUONG = 'BD',
    BAO_HANH = 'BH',
    KHAO_SAT = 'KS',
    TAI_LAP_DAT = 'TLD',
    SUA_CHUA = 'SC',
    KHAC = 'KHAC',
    THAY_THE_LOI_LOC = 'TTLL',
    LAP_BOM_TANG_AP = 'LBTA',
    LAP_PRE_FILTER = 'LPF',
    KM_BO_LOC_PRE_FILTER = 'KMP',
    DOI_CAU_HINH_MAY = 'DCHM',
    HAPPY_CALL = 'Happycall',
    GIAI_QUYET_KHIEU_NAI = 'PN',
    TAI_LAP_DAT_BOM = 'TLB',
    KIEM_NGHIEM_NUOC = 'KNN',
    THAO_MAY = 'TM',


    //Saigon Newport
    SAIGON_NEWPORT = 'SAIGON_NEWPORT',
    GATE_IN = 'GATE_IN',
    LIFT_ON_1 = 'LIFT_ON_(1)',
    GATE_OUT = 'GATE_OUT',
    LIFT_ON_0 = 'LIFT_ON_(0)',
    LIFT_OFF = 'LIFT_OFF',
    STUFFING_START = 'STUFFING_START',
    STUFFING_FINISH = 'STUFFING_FINISH',
    DESTUFFING_START = 'DESTUFFING_START',
    DESTUFFING_FINISH = 'DESTUFFING_FINISH',
    TRAILER_ATTACH = 'TRAILER_ATTACH',
    TRAILER_DETACH = 'TRAILER_DETACH',
    CHARGE_FEE = 'CHARGE_FEE',

    SHIPPING_STARTED = 'SHIPPING_STARTED',
    SHIPPING_COMPLETED = 'SHIPPING_COMPLETED',

    IN_PORT = "IN_PORT",
    IN_WHARVES = "IN_WHARVES",
    OUT_WHARVES = "OUT_WHARVES",
    LINED_UP_STARTED = 'LINED_UP_STARTED',
    LINED_UP_COMPLETED = 'LINED_UP_COMPLETED',
    OUT_PORT = 'OUT_PORT',
    UNLOAD_STARTED = 'UNLOAD_STARTED',
    UNLOAD_COMPLETED = 'UNLOAD_COMPLETED',
    OTHER_TASK = 'OTHER_TASK',

    //Depot Task
    DEPOT_RECEIVING = 'DEPOT_RECEIVING',
    DEPOT_DELIVERY = 'DEPOT_DELIVERY'
};

export default TaskCode;