export default {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    CHECK_IN: 'CHECK_IN',
    APP_OFFLINE: 'APP_OFFLINE',
    APP_ONLINE: 'APP_ONLINE',
    GPS_OFF: 'GPS_OFF',
    GPS_ON: 'GPS_ON',
    APP_LAUNCH: 'APP_LAUNCH',
    APP_EXIT: 'APP_EXIT',
    START_TRACKING: 'START_TRACKING',
    STOP_TRACKING: 'STOP_TRACKING',
    LOAD_IMAGE: 'LOAD_IMAGE_ERROR',
}