// Product
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';


export const CHANGE_SKU_NUMBER = 'CHANGE_SKU_NUMBER';
export const CHANGE_DISCOUNT = 'CHANGE_DISCOUNT';

export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST';
export const FETCH_CATEGORY_START = 'FETCH_CATEGORY_START';
