// Fetch Data

export const FETCH_TASK_LIST_START = 'FETCH_TASK_LIST_START';
export const FETCH_TASK_LIST = 'FETCH_TASK_LIST';
export const FETCH_TASK_LIST_ERROR = 'FETCH_TASK_LIST_ERROR';

export const FETCH_TASK_DETAIL = 'FETCH_TASK_DETAIL';
export const FETCH_TASK_ORDERS = 'FETCH_TASK_ORDERS';
export const FETCH_TASK_DETAIL_START = 'FETCH_TASK_DETAIL_START';
export const FETCH_TASK_DETAIL_ERROR = 'FETCH_TASK_DETAIL_ERROR';
export const FETCH_PROMOTION_VFAST = 'FETCH_PROMOTION_VFAST';
export const FETCH_PROMOTION_INITIATIVE = 'FETCH_PROMOTION_INITIATIVE';


export const RESET_TASK_DETAIL = 'RESET_TASK_DETAIL';
export const EDIT_TASK_DETAIL = 'EDIT_TASK_DETAIL';

export const RELOAD_TASK_LIST = 'RELOAD_TASK_LIST';

// TASK

export const LOAD_TASK = 'LOAD_TASK';
export const ADD_TASK_RESULT = 'ADD_TASK_RESULT';
export const READ_TASK = 'READ_TASK';
export const LOAD_TASK_DETAIL = 'LOAD_TASK_DETAIL';


