export default {
    iconAbivinBlue: require('./icon/iconAbivinBlue.png'),
    iconAbivinWhite: require('./icon/iconAbivinWhite.png'),
    iconBike: require('./icon/iconBike.png'),
    iconBookmark: require('./icon/iconBookmark.png'),
    iconBookmarkOutline: require('./icon/iconBookmarkOutline.png'),
    iconCase: require('./icon/iconCase.png'),
    iconCaseHint: require('./icon/iconCaseHint.png'),
    iconChargeList: require('./icon/iconChargeList.png'),
    iconContainer: require('./icon/iconContainer.png'),
    iconCurrentLocation: require('./icon/iconCurrentLocation.png'),
    iconFingerPrint: require('./icon/iconFingerPrint.png'),
    iconItem: require('./icon/iconItem.png'),
    iconItemHint: require('./icon/iconItemHint.png'),
    iconPerson: require('./icon/iconPerson.png'),
    iconSecurity: require('./icon/iconSecurity.png'),
    iconShip: require('./icon/iconShip.png'),
    iconTrailer: require('./icon/iconTrailer.png'),
    iconTrailerDetach: require('./icon/iconTrailerDetach.png'),
    iconTruck: require('./icon/iconTruck.png'),

    customer: require('./icon/tabs/customer.png'),
    freight: require('./icon/tabs/freight.png'),
    order: require('./icon/tabs/order.png'),
    product: require('./icon/tabs/product.png'),
    setting: require('./icon/tabs/setting.png'),
    shipment: require('./icon/tabs/shipment.png'),
    shipmentHistory: require('./icon/tabs/shipmentHistory.png'),
    task: require('./icon/tabs/task.png'),
    iconInfoTask: require('./icon/notification/iconInfoTask.png'),
    iconWarningTask: require('./icon/notification/iconWarningTask.png'),
}